[app]
path=combined
fullscreen=true
kiosk=true

[debug]
show_menu = false   ; SAKRIVA MENI
dev_tools = false   ; ISKLJUČUJE DEVTOOLS

; Konfiguracija check-in vremena za aviokompanije
; Format: airline_CODE = MINUTA_PRIJE_POLASKA
[checkin]
; Specijalne aviokompanije (3 sata = 180 minuta)
6H = 180    ; ISRAIR
FZ = 180    ; Flydubai
TK = 120    ; Turkish Airlines (iako je 120 default, može se eksplicitno navesti)
JU = 120    ; Air Serbia
LH = 120    ; Lufthansa
BA = 120    ; British Airways
4O = 120    ; Air Montenegro
FR = 120    ; Ryanair
U2 = 120    ; EasyJet
LS = 150    ; JET2
EC = 120    ; EasyJet
DS = 120    ; EasyJet
LY = 180    ; SUNDOR EL AL
IZ = 180    ; ARKIA

; Default vrijeme za sve ostale aviokompanije (2 sata = 120 minuta)
default = 120
